(load "~/.emacs.d/config/config.el")
(load-config "parameters")
(load-config "ui")
(load-config "global-set-key")
(load-config "speedbar")
(load-config "eshell")
(load-config "color-theme")
(load-config "ediff")

(load-config "w3m")
(load-config "erc")
(load-config "dired")
(load-config "session")
(load-config "desktop")
(load-config "linum")
(load-config "org")
(load-config "uniquify")
(load-config "slime")
(load-config "emms")
(load-config "ess")
(load-config "maxima")
(load-config "egg")
(load-config "cedet")
(load-config "ecb")
(load-config "compile")

(load-config "cc-mode")
(load-config "interactive-mode")
(load-config "python-mode")
(load-config "texinfo-mode")

;; xcscope
;(require 'xcscope)

