cmake_minimum_required(VERSION 3.15)

project(__PROJECT-NAME__ VERSION 0.0.1 LANGUAGES CXX)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

find_package(SWIG REQUIRED)
find_package(lua REQUIRED)
find_package(SQLite3 REQUIRED)
find_package(spdlog REQUIRED)
find_package(doctest REQUIRED)

set(DEP_LIBS SQLite::SQLite3 doctest::doctest lua::lua spdlog::spdlog)

set(SWIG_CXX_OUTPUT lib_wrap.cpp)
set(SOURCE_FILES src/main.cpp src/lib.cpp ${CMAKE_CURRENT_BINARY_DIR}/${SWIG_CXX_OUTPUT})
set(TEST_SOURCE_FILES test/main.cpp src/lib.cpp ${CMAKE_CURRENT_BINARY_DIR}/${SWIG_CXX_OUTPUT})
set(SWIG_SOURCE src/lib.i)

set_source_files_properties(
  src/lib.i PROPERTIES
  CPLUSPLUS ON
  SWIG_FLAGS "-includeall"
  SWIG_USE_TARGET_INCLUDE_DIRECTORIES ON)

add_custom_command(
  OUTPUT ${SWIG_CXX_OUTPUT}
  COMMAND "${SWIG_EXECUTABLE}"
  ARGS -Wall -c++ -includeall -lua
  -I${CMAKE_CURRENT_SOURCE_DIR}/include
  -o ${CMAKE_CURRENT_BINARY_DIR}/${SWIG_CXX_OUTPUT}
  ${CMAKE_CURRENT_SOURCE_DIR}/${SWIG_SOURCE}
  DEPENDS ${SWIG_SOURCE} include/lib.h
  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
  VERBATIM)

add_executable(${PROJECT_NAME} ${SOURCE_FILES})
target_include_directories(
  ${PROJECT_NAME}
  PUBLIC
  "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>"
  "$<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>"
  $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
target_link_libraries(${PROJECT_NAME} PRIVATE ${DEP_LIBS})

set(TEST_PROJECT_NAME ${PROJECT_NAME}-test)
add_executable(${TEST_PROJECT_NAME} ${TEST_SOURCE_FILES})
target_include_directories(
  ${TEST_PROJECT_NAME}
  PUBLIC
  "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>"
  "$<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>"
  $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
target_link_libraries(${TEST_PROJECT_NAME} PRIVATE ${DEP_LIBS})

include(CTest)
add_test(NAME ${PROJECT_NAME}-Unit-Tests COMMAND ${TEST_PROJECT_NAME})

include(GNUInstallDirs)
set_target_properties(${PROJECT_NAME} PROPERTIES DEBUG_POSTFIX "d")

install(
  TARGETS ${PROJECT_NAME}
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
